# Site settings
title: Stevenson Lofts
email: rentals@relisto.com
description: > # this means to ignore newlines until "baseurl:"
  The team at ReLISTO has teamed up with the owners of Stevenson Lofts to help you find better housing. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "dannyshafer.github.io/Stevenson-early" # the base hostname & protocol for your site
twitter_username: StevensonLofts
github_username:  dannyshafer

# Build settings
markdown: kramdown
